// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS8_Q0At1jCGo_3YHVEMJ2wBwjDvKpx-U',
    appId: '1:604187390204:web:f541e746494f7fdc862779',
    messagingSenderId: '604187390204',
    projectId: 'shopify-9c6d0',
    authDomain: 'shopify-9c6d0.firebaseapp.com',
    storageBucket: 'shopify-9c6d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvlTc-3fmZ_7NAudZMFR_5K2oAGukxM6E',
    appId: '1:604187390204:android:db83ed2abc6a6f2e862779',
    messagingSenderId: '604187390204',
    projectId: 'shopify-9c6d0',
    storageBucket: 'shopify-9c6d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtwL7QLYZo2mPauXFhZNn4FjMJ8Yx9wno',
    appId: '1:604187390204:ios:5dc82b9a08f4034b862779',
    messagingSenderId: '604187390204',
    projectId: 'shopify-9c6d0',
    storageBucket: 'shopify-9c6d0.appspot.com',
    iosBundleId: 'com.example.shoppfiyProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtwL7QLYZo2mPauXFhZNn4FjMJ8Yx9wno',
    appId: '1:604187390204:ios:6cd01db016148480862779',
    messagingSenderId: '604187390204',
    projectId: 'shopify-9c6d0',
    storageBucket: 'shopify-9c6d0.appspot.com',
    iosBundleId: 'com.example.shoppfiyProvider.RunnerTests',
  );
}
